version: '3.9'

services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"  # 외부 → 내부
    depends_on:
      - auth-service
      - user-service
      - team-service
      - project-service
      - notification-service
    networks:
      - app-network

  auth-service:
    build: auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    networks:
      - app-network

  user-service:
    build: user-service
    container_name: user-service
    ports:
      - "8002:8000"
    networks:
      - app-network

  team-service:
    build: team-service
    container_name: team-service
    ports:
      - "8003:8000"
    networks:
      - app-network

  project-service:
    build: project-service
    container_name: project-service
    ports:
      - "8004:8000"
    networks:
      - app-network

  notification-service:
    build: notification-service
    container_name: notification-service
    ports:
      - "8005:8000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
